### ISSUE TITLE
基本上现在都是脚本大战了= =

### ISSUE THREAD

**Issue by tianyu-su** [blackcatrecycler/UselessNet#1]

**Comment by blackcatrecycler** [comment]
确实: )
不然你的程序就会被无脑停掉

**Comment by tianyu-su** [comment]
UselessNet ～ Unet

**Comment by GeoffreyChen777** [comment]
很cool，但是实际上后台还有很多监控没有打开，另外，意义何在呢= =GPU占满了无用的计算卡在那里，然后自己ssh进去跑实验也跑不动- - emmmm

**Comment by GeoffreyChen777** [comment]
BTW，监控是可以看平均利用率，而不是点利用率的

**Comment by blackcatrecycler** [comment]
> BTW，监控是可以看平均利用率，而不是点利用率的

然而，我推荐秦老爷子的gpu课程=。=，gpu的利用率计算很粗暴的

**Comment by GeoffreyChen777** [comment]
> > BTW，监控是可以看平均利用率，而不是点利用率的
> 
> 然而，我推荐秦老爷子的gpu课程=。=，gpu的利用率计算很粗暴的

无所谓啊，你就算是再怎么折腾，随意弄就是，反正本身监控的作用是为了公平使用，每个人都需要跑实验，而不是一个人可以卡在那里永远不释放，本身各种规则都有漏洞，如果你想钻，那也无所谓去钻就好了，所有人看在眼里

**Comment by blackcatrecycler** [comment]
> > > BTW，监控是可以看平均利用率，而不是点利用率的
> > 
> > 
> > 然而，我推荐秦老爷子的gpu课程=。=，gpu的利用率计算很粗暴的
> 
> 无所谓啊，你就算是再怎么折腾，随意弄就是，反正本身监控的作用是为了公平使用，每个人都需要跑实验，而不是一个人可以卡在那里永远不释放，本身各种规则都有漏洞，如果你想钻，那也无所谓去钻就好了，所有人看在眼里

有些人，无所谓了半天=。=还不如开个issue给我刷刷数据也好啊XD
